In [1]:
import numpy as np
import pandas as pd
students = np.random.randint(50, 101, size=(50,5))
stu= pd.DataFrame(students, 
             columns=["國文","英語","數學","地理","歷史"],
             index=[f"第{i}號" for i in range (1,51)])
stu

       國文   英語   數學  地理   歷史
第1號    58   72   97  86   79
第2號    62   82   77  98   74
第3號    90   60   97  83   85
第4號    73   64   76  57   91
第5號    85   68   87  57  100
第6號    92   59   79  72   72
第7號    79   65   90  58   66
第8號    88   98   54  67   91
第9號    68   64   56  65   88
第10號   72   63   88  87   95
第11號   83   82   64  68   94
第12號   97   64   65  92   58
第13號   83   97  100  97   81
第14號   88   55   83  95   76
第15號   83   59   99  73   97
第16號   77   99   55  61   89
第17號   85   87   82  56   57
第18號   51   95   66  70   83
第19號   94   60   70  99   86
第20號   67   54   73  96   95
第21號   95   71   70  68   58
第22號   60   71   95  86  100
第23號   79   66   91  50   52
第24號   71   85   77  64   50
第25號   82   88   74  53   55
第26號   90   75   81  59   84
第27號   72   65   86  80   81
第28號   90   81   54  80   79
第29號   74   70   58  74   76
第30號   76   57   85  97   94
第31號   55   57   66  87   68
第32號   86   74   96  64   80
第33號   99   81   91  63   71
第34號   56   96   86  64   94
第35號   52   94   65  59   56
第36號   72   80   58  61  100
第37號   52  100   57  51   87
第38號   60   66   91  69   75
第39號   67   99   89  60   53
第40號  100   92   88  63   71
第41號   97   57   91  59   97
第42號   81   59   85  69   73
第43號   71   87   84  53   80
第44號   81   83   56  68   80
第45號   79   87   65  82   91
第46號   88   87   54  91   68
第47號   69   54   54  70   56
第48號   55   64   64  59   64
第49號   55   97   86  93   85
第50號   86   64   80  67   74

In [8]:
#Series
chinese_series = stu["國文"]
chinese_series

第1號      58
第2號      62
第3號      90
第4號      73
第5號      85
第6號      92
第7號      79
第8號      88
第9號      68
第10號     72
第11號     83
第12號     97
第13號     83
第14號     88
第15號     83
第16號     77
第17號     85
第18號     51
第19號     94
第20號     67
第21號     95
第22號     60
第23號     79
第24號     71
第25號     82
第26號     90
第27號     72
第28號     90
第29號     74
第30號     76
第31號     55
第32號     86
第33號     99
第34號     56
第35號     52
第36號     72
第37號     52
第38號     60
第39號     67
第40號    100
第41號     97
第42號     81
第43號     71
第44號     81
第45號     79
第46號     88
第47號     69
第48號     55
第49號     55
第50號     86
Name: 國文, dtype: int64

In [5]:
chinese_series["第49號"]    #第49號國文的成績

55

In [6]:
chinese_series[["第49號","第50號"]]  #第49號和第50號的國文成績

第49號    55
第50號    86
Name: 國文, dtype: int64

In [10]:
chinese_series[:5] #國文前5個學生的分數

第1號    58
第2號    62
第3號    90
第4號    73
第5號    85
Name: 國文, dtype: int64

In [12]:
#第一和第二號學生
stu.loc[["第1號","第2號"]]

     國文  英語  數學  地理  歷史
第1號  58  72  97  86  79
第2號  62  82  77  98  74

In [13]:
#前5個學生
stu.iloc[:5]
#後5個學生
stu.iloc[-5:]

      國文  英語  數學  地理  歷史
第46號  88  87  54  91  68
第47號  69  54  54  70  56
第48號  55  64  64  59  64
第49號  55  97  86  93  85
第50號  86  64  80  67  74